name: release

on:
  push:
     branches:
      - main
      - feat/release-action

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: stable
      - name: sent env
        run: |
          echo "CURDATE=$(date '+%Y%d%m%s')" >> $GITHUB_ENV
      - name: Create tag
        run: |
          git tag $CURDATE
          git push origin $curdate
      - name: Build
        run: |
          make
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: $CURDATE
          files: build/*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

