name: release
on:
  push:
    branches:
      - main
      - feat/release-action
    tags:
      - '**'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Build
        run: |
          make release
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: build/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

