name: release

on:
  push:
    tags:
      - "20*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Build
        run: |
          make
      - name: Checkout tag
        run: |
          git switch --detach "$CURDATE"     
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: build/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

